use burn::backend::NdArray;
use burn::config::Config;
use burn::module::Module;
use burn::nn::conv::{Conv2d, Conv2dConfig};
use burn::nn::pool::{AdaptiveAvgPool2d, AdaptiveAvgPool2dConfig, MaxPool2d, MaxPool2dConfig};
use burn::nn::{Linear, LinearConfig, PaddingConfig2d};
use burn::optim::AdamConfig;
use burn::tensor::backend::Backend;

// --- the model, now built from a Config ---
#[derive(Config, Debug)]
struct SmallCnnConfig {
    #[config(default = 4)]
    channels1: usize,
    #[config(default = 8)]
    channels2: usize,
    #[config(default = 4)]
    classes: usize,
}

impl SmallCnnConfig {
    fn init<B: Backend>(&self, device: &B::Device) -> SmallCnn<B> {
        let same = PaddingConfig2d::Explicit(1, 1, 1, 1);
        SmallCnn {
            conv1: Conv2dConfig::new([1, self.channels1], [3, 3])
                .with_padding(same.clone())
                .init(device),
            pool: MaxPool2dConfig::new([2, 2]).init(),
            conv2: Conv2dConfig::new([self.channels1, self.channels2], [3, 3])
                .with_padding(same)
                .init(device),
            gap: AdaptiveAvgPool2dConfig::new([1, 1]).init(),
            head: LinearConfig::new(self.channels2, self.classes).init(device),
        }
    }
}

#[derive(Module, Debug)]
struct SmallCnn<B: Backend> {
    conv1: Conv2d<B>,
    pool: MaxPool2d,
    conv2: Conv2d<B>,
    gap: AdaptiveAvgPool2d,
    head: Linear<B>,
}

// Everything a training run depends on, in one serialisable value.
#[derive(Config, Debug)]
struct TrainingConfig {
    model: SmallCnnConfig,
    optimizer: AdamConfig,
    #[config(default = 15)]
    num_epochs: usize,
    #[config(default = 16)]
    batch_size: usize,
    #[config(default = 0.02)]
    learning_rate: f64,
}

/// Returns (the saved JSON, params of the default model, params with channels2 = 16, epochs read back).
fn build() -> (String, usize, usize, usize) {
    let device = Default::default();
    let config = TrainingConfig::new(SmallCnnConfig::new(), AdamConfig::new().with_epsilon(1e-8));

    // A Config saves to JSON and loads back. The file IS the experiment's settings.
    let path = std::env::temp_dir().join("learning-burn-c18e1-config.json");
    config.save(&path).expect("save config");
    let json = std::fs::read_to_string(&path).unwrap();
    let loaded = TrainingConfig::load(&path).expect("load config");

    // The model is built FROM its config, so the file is enough to rebuild it.
    let model: SmallCnn<NdArray> = loaded.model.init(&device);
    // Every field has a with_ method, generated by #[derive(Config)].
    let wider: SmallCnn<NdArray> = loaded.model.clone().with_channels2(16).init(&device);
    (
        json,
        model.num_params(),
        wider.num_params(),
        loaded.num_epochs,
    )
}

fn main() {
    let (json, params, wider, epochs) = build();
    println!("{json}");
    println!("epochs read back       = {epochs}");
    println!("default model params   = {params}");
    println!("channels2 = 16, params = {wider}");
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn matches_pytorch() {
        let (json, params, wider, epochs) = build();
        assert_eq!((params, wider, epochs), (372, 700, 15));
        assert!(json.contains("\"learning_rate\": 0.02"));
        assert!(json.contains("\"channels2\": 8"));
    }
}
